server:
  api: "localhost:4000"
  debug: "localhost:4010"
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "120s"
  shutdownTimeout: "20s"
  corsAllowedOrigins: "*"
db:
  name: "housi_db"
  user: "housi"
  password: "secret123"
  host: "localhost:5432"
  maxOpenConnections: "25"
  maxIdleConnections: "25"
  connectionIdleTime: "30s"
  disableTLS: true
otel:
  host: "localhost:3200"
  reporterURI: "/debug"
  probability: "0.05"
prometheus:
  host: "localhost:9090"
  route: "/metrics-test"
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "120s"
  shutdownTimeout: "5s"
collect:
  from: "http://localhost:4010/debug/vars"
publish:
  to: "console"
  interval: "5s"
