version: '3.8'

services:
  db:
    image: postgres:15.4
    container_name: db-container
    restart: always
    environment:
      POSTGRES_DB: "${DB_DATABASE:-housi}"
      POSTGRES_USER: "${DB_USER:-housi}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret123}"
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - app_local_network

  redis:
    image: redis:latest
    container_name: redis-container
    command: /bin/sh -c 'redis-server --requirepass ${REDIS_PASSWORD:-secret123}'
    volumes:
      - app_redis_data:/var/lib/redis/data
    ports:
      - "6379:6379"
    networks:
      - app_local_network

  migrate:
    container_name: migrate-container
    build:
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
      context: .
      dockerfile: .docker/migrate/Dockerfile
    volumes:
      - .:/app
    networks:
      - app_local_network

networks:
  app_local_network:

volumes:
  app_db_data:
  app_redis_data:
