version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db-container
    restart: always
    environment:
      POSTGRES_DB: "housi_db"
      POSTGRES_USER: "housi"
      POSTGRES_PASSWORD: "secret123"
    ports:
      - "5432:5432"
    volumes:
      - db_data_v:/var/lib/postgresql/data
    networks:
      - app_local_network

  redis:
    image: redis:latest
    container_name: redis-container
    command: /bin/sh -c 'redis-server --requirepass ${REDIS_PASSWORD:-secret123}'
    volumes:
      - redis_data_v:/var/lib/redis/data
    ports:
      - "6379:6379"
    networks:
      - app_local_network

  migrate:
    container_name: migrate-container
    build:
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
      context: .
      dockerfile: .docker/migrate/Dockerfile
    volumes:
      - .:/app
    networks:
      - app_local_network

networks:
  app_local_network:

volumes:
  db_data_v:
  redis_data_v:
