version: '3.8'

services:
  db:
    image: postgres:15.4
    container_name: db-container
    restart: always
    environment:
      POSTGRES_DB: "housi_db"
      POSTGRES_USER: "housi"
      POSTGRES_PASSWORD: "secret123"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_local_network

  migrate:
    container_name: migrate-container
    build:
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
      context: .
      dockerfile: .docker/migrate/Dockerfile
    volumes:
      - .:/app
    networks:
      - app_local_network

networks:
  app_local_network:

volumes:
  db_data:
