version: '3.8'

services:
    db:
        image: postgres:13
        container_name: simple-banking-db-container
        restart: always
        environment:
            POSTGRES_DB: "${DB_DATABASE:-housi_db}"
            POSTGRES_USER: "${DB_USER:-housi}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret123}"
        ports:
            - '${DB_PORT:-5432}:5432'
        volumes:
            - simple_banking_db_data:/var/lib/postgresql/data
        networks:
            - simple_banking_local_network

    redis:
        image: redis:latest
        container_name: simple-banking-redis-container
        command: /bin/sh -c 'redis-server --requirepass ${REDIS_PASSWORD:-secret123}'
        volumes:
            - simple_banking_redis_data:/var/lib/redis/data
        ports:
            - "6379:6379"
        networks:
            - simple_banking_local_network

    utility:
        container_name: utility-container
        image: simple-banking/utility
        build:
            args:
                USER: "localdev"
                UID: "${UID:-1000}"
            context: ../../
            dockerfile: .docker/local/utility/Dockerfile
        volumes:
            - ../../:/app
        networks:
            - simple_banking_local_network

networks:
    simple_banking_local_network:

volumes:
    simple_banking_db_data:
    simple_banking_redis_data:
